Azure/azure-api-style-guide

functions/unique-param-names.js
the currently used `value` variable in the canonical function is
inherited from global scope and might not reference the same value as
`name` when the function is called.
`name` is scoped to the function so it is better/correct to use
`name` here.
=> changes typeof parameter in canonical function

functions/has-header.js, spectral.yaml, test/lro-headers.test.js
This PR fixes the `az-lro-headers` rule to check for `operation-location` case insensitively.  It also adds a new test to verify correct behavior.
Fixes #6
=> Fix az-lro-headers to check header name case-insensitively

docs/azure-ruleset.md, spectral.yaml, test/request-body-optional.test.js
This PR adds a check for a put, patch, or post request body (body parameter in oas2) that is not marked as required.  This is not necessarily wrong but very unusual and a common oversight.  Tests included.
=> Add rule and test for request body not required

spectral.yaml
This PR changes the severity of three rules from "hint" to "info" so that they will appear in VSCode.  We previously were not using "info" for any rules so we still have 3 categories of rules -- just using a different name for the third category.
=> Use info rather than hint for better VSCode integration

docs/azure-ruleset.md, spectral.yaml
A tiny PR to add a simple rule to check for the use of the `x-ms-paths` autorest extension in an API document. This extension is helpful for supporting legacy APIs that were designed prior to OpenAPI, but should otherwise be avoided if at all possible.
=> Add az-ms-paths rule

docs/azure-ruleset.md, spectral.yaml, test/header-disallowed.test.js
This PR adds a rule to flag header parameters `Authorization`, `Content-Type`, or `Accept`.  These parameters should not be defined explicitly since their definition is implied by other elements of the API definition.
The [OpenAPI 3 specification](https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#fixed-fields-10) explicitly states that these header definitions should be ignored.
=> Add az-header-disallowed rule

docs/azure-ruleset.md, spectral.yaml
This PR adds a simple rule to flag uses of the Autorest `x-nullable` extension.
=> Add az-nullable rule to flag instances of x-nullable

spectral.yaml, test/additional-properties-object.test.js
This is a small bug-fix PR for the az-additional-properties-object rule.  The prior code flagged cases where additional properties is an object with defined properties -- but that case is perfectly fine.  We only want to flag cases where additionalProperties is a simple object with no properties.
Sadly this rule does not currently work with Spectral v6+.  There is an issue open -- several people have reported similar problems.
https://github.com/stoplightio/spectral/issues/1920
Thankfully the VSCode extension is still using the v5.9 version and it works just fine.  I also added a test which seems to work fine.
=> Fix additional-properties-object rule

docs/azure-ruleset.md, spectral.yaml
Another simple rule, level "info", to flag formData parameters to check for proper use.
=> Add az-formdata rule to suggest check on formData parameters

openapi-style-guide.md, spectral.yaml, test/additional-properties-object.test.js
This PR fixes the `az-additional-properties-object` rule when using Spectral v6+.
The JSON Path used in this rule had a subtle bug -- only looking at immediate children of root rather than recursing with "..".
Spectral v5.9 apparently mis-interpreted the single "." because it found occurrences that were not immediate children of root.  Spectral v6 fixed that, which exposed the bug in the rule.
With this fix, the rule works correctly in both Spectral v5.9 and Spectral v6+.
I also added some tests.
I've pushed a few more small changes into this PR:
- The az-additional-properties-and-properties rule was causing a Spectral error if the API def contains a "null".  The fix is to check that the element is an object before inspecting its properties.
- The az-additional-properties-object rule was …
=> Fix additional-properties-object rule in Spectral v6+

docs/azure-ruleset.md, spectral.yaml, test/security-definition-description.test.js
This PR adds a simple rule to check that all security definitions / security schemes contain a description.
This rule should work for both oas2 and oas3 API definitions.
Tests included.
=> Add az-security-definition-description rule

README.md
ref to `openapi-style-guide`
add link for `openapis.org` spec
update OAS version text 2.0 > 3.1
=> fix: update invalid links

functions/version-policy.js, test/header-disallowed.test.js
This PR fixes the az-version-policy rule to drop the check on the `default` value for `api-version`.
Previously az-version-policy was checking the value of `default`, but this was inconsistent with the az-parameter-default-not-allowed rule that says required parameters should not have a default.
Tests are updated.
=> Drop check for default value in az-version-policy rule

.github/workflows/node.js.yml, README.md, package.json
This PR adds a GitHub action to run test and lint on PRs to the main branch. I updated the jest config to require a minimum statement coverage of 80%.
I also discovered that some functions are using "optional chaining" which is not supported in Node 12, so I updated the README.md to say that Node 14+ is required.
=> Add Github action to test and lint

docs/azure-ruleset.md, functions/param-order.js, openapi-style-guide.md, spectral.yaml, test/parameter-order.test.js
This PR adds a rule to check that the order of path parameters in the parameter list (both at the path-item and operation level) is consistent with the order of path parameters in the path template.
For example, all the operations for path:
```
"paths": {
"/foo/{p1}/bar/{p2}/baz/{p3}": {
```
should have `p1` before `p2` before `p3` in its parameter list.
This ordering helps make generated methods for these operations more natural and provides consistency across services.
Fixes #19
=> Add az-param-order rule

spectral.yaml, test/property-description.test.js
This PR fixes a crash caused by the `az-property-description` rule that occurs when there is a property named "properties", which actually happens quite frequently. Before this fix, Spectral would simply fail with the message:
```
Cannot read property '$ref' of null
```
because it was trying to access a property of a non-object.  The fix is simply to check that the element is an object before trying to reference its fields.
Unfortunately, this causes problems with our test framework, where we are converting the yaml ruleset into the new JS format so that we can disable rules.  I have tried fixing our test setup code but so far have been unsuccessful.  So for now I have just disabled the tests for this particular rule.  I have tested the rule manually and confirmed that it works as …
=> fix az-property-description to handle properties named "properties"

docs/azure-ruleset.md, docs/crossref.md, openapi-style-guide.md, spectral.yaml
This PR adds a simple rule (yaml only) to check that an operation that returns a 202 response is marked with `x-ms-long-running-operation: true`.
=> Add az-lro-extension rule

package-lock.json, package.json, test/property-description.test.js
After much trial and error I discovered the magic needed to be able to run the `az-property-description` tests successfully.
As a bonus, updating the spectral packages has resolved all the outstanding npm audit issues.
Fixes #47
=> Fix test setup and re-enable property-description tests

docs/azure-ruleset.md, functions/path-param-schema.js, openapi-style-guide.md, spectral.yaml, test/path-param-schema.test.js
This PR adds a rule to check that path parameters are type: string and specify a maxLength and pattern to define the set of allowed characters.
=> Add az-path-parameter-schema rule

docs/azure-ruleset.md, functions/path-param-names.js, openapi-style-guide.md, spectral.yaml, test/path-param-names.test.js
This PR adds a rule to check that path parameter names are consistent across all paths.
The rationale for this rule is that a path parameter is generally a "resource id" -- specifically for the resource named by the path segment that immediately precedes the parameter in the path. And we should use a consistent name for this id across all the paths.
=> Add az-path-parameter-names rule with doc and tests.

functions/pagination-response.js
This PR eliminates the crash that was occurring in the `pagination-response` function when the response schema did not have `properties`.  All the properties of the schema are within the child schemas of an `allOf`.
I opened #57 to track the work for `pagination-response` to check in an `allOf` when looking for the `value` and nextLink properties.
This PR just adds guards to ensure that `pagination-response` function does not crash if there is no `properties` object in the response scheam.
=> Check properties exists in responseSchema before access

docs/azure-ruleset.md, spectral.yaml
This PR adds a rule to check an api-version parameter for an enum and warn when one is found.
=> Add az-api-version-enum rule

openapi-style-guide.md, spectral.yaml
This PR adds the az-property-type rule that warns on any named property (not additionalProperties) that does not specify a `type`.
=> Add az-property-type rule

docs/azure-ruleset.md, spectral.yaml
Add a simple rule to flag uses of x-ms-client-flatten.  The use of this extension is discouraged because it can cause breaking changes in generated SDK from API changes that are not breaking.
=> Add az-ms-client-flatten rule

docs/azure-ruleset.md, spectral.yaml
This PR adds a simple rule to check the top-level schema of a response body to ensure it is not `type: array`. 
Array types are problematic because you cannot add a property (such as `nextLink`) later without making an incompatible change.
It looks like there are many violations of this rule in existing GA'd Azure services. Here's a sampling:
- specification/cognitiveservices/data-plane/ContentModerator/stable/v1.0/ContentModerator.json
- specification/cognitiveservices/data-plane/CustomVision/Training/stable/v3.3/Training.json
- specification/cognitiveservices/data-plane/Face/stable/v1.0/Face.json
- specification/cognitiveservices/data-plane/LUIS/Authoring/stable/v3.0/LUIS-Authoring.json
- specification/cognitiveservices/data-plane/Personalizer/stable/v1.0/Personalizer.json
- …
=> Add az-response-body-type rule

functions/path-param-names.js, test/path-param-names.test.js
This PR improves the az-path-param-names rule by checking that the path segment that precedes a particular path parameter is the same across all paths.  This is the inverse of the check that was already implemented in this rule.
I discovered that this case was missing when reviewing PR 17817.
=> Improve the az-path-param-names rule

docs/azure-ruleset.md, functions/security-definitions.js, openapi-style-guide.md, spectral.yaml, test/security-definitions.test.js
This PR adds the az-security-definitions rule which checks that security schemes in `securityDefinitions` contain the information needed by autorest to produce client libraries with the correct authentication features.
This is a new requirement for data plane codegen and currently most Azure services are not in compliance, particularly in regard to the presence of scopes and pattern of scope names.
=> Add az-security-definitions rule

docs/azure-ruleset.md, functions/schema-type-and-format.js, spectral.yaml, test/schema-type-and-format.test.js
This PR adds a rule to check that the type and format combination for a schema is well-defined.
=> Add az-schema-type-and-format rule with tests and doc

spectral.yaml, test/security-requirements.test.js
This PR is a temporary workaround for problems with the ruleset when run on an oas3 format API definition.
I've opened #90 to document the problems and we should debug/fix those at some point, but for now this PR just disables these problematic rules for oas3 to allow the rest of the rules to run.
=> Disable oas3 format for rules that now fail for oas3

spectral.yaml, test/path-case-convention.test.js, test/path-characters.test.js
This PR adds the az-path-case-convention rule that checks static path segments to ensure they are kebab-case.
=> Add az-path-case-convention rule and test

docs/azure-ruleset.md, functions/operation-id.js, openapi-style-guide.md, test/operation-id.test.js
This PR is a significant revamp of the az-operation-id checks.
The new logic uses the status codes to determine which verbs should and should not appear for put and patch. The logic for get was changed to use the final path segment to determine whether the verb should be "get" or "list".
Tests and docs are all updated.
=> Improve style and checks for operationIds

functions/path-param-schema.js, spectral.yaml, test/path-param-schema.test.js
The PR makes some minor improvements to the az-path-parameter-schema rule. In particular, it now only flags missing constraints on the final path parameter of a put or patch that returns 201, since these are case where the user is specifying a new value for the parameter, as opposed to the id of an existing resource.
=> Improvements to az-path-parameter-schema

docs/azure-ruleset.md, functions/error-response.js, spectral.yaml, test/error-code-response-header.test.js, test/error-response.test.js
This PR moves the check for the x-ms-error-code response header out of az-error-response to a new rule, az-error-code-response-header.
This change will allow users to selectively disable the az-error-code-response-header check without disabling all checking on the error response.
=> Split error-code-response-header into its own rule

docs/azure-ruleset.md, spectral.yaml
This PR adds a simple rule to check that all values in an x-ms-enum extension have a "description".  This will improve the quality of the generated REST API docs.
=> Add az-ms-enum-descriptions rule to check for descriptions on enums

docs/azure-ruleset.md, spectral.yaml
This PR adds a simple rule to check that the final path segment of the path for a patch operation is a path parameter.
There is already a similar rule that checks put operations.
I made both of these rules "info" since there are legitimate cases for put or patch on a path that does not end in a path parameter.
I expanded the documentation a bit to explain the motivation of these two rules.
=> Add az-patch-path rule

functions/error-response.js, test/error-response.test.js
This PR skips the message for missing error response schema for head operations.
=> No msg for missing error response schema for head request

functions/path-param-names.js, test/path-param-names.test.js
This PR backs out the change made in #83 that flags any path parameter name that is used for more than one path segment. This rule was over-zealous and fires when multiple resources use a common name like "id" as the path parameter name.
=> Back out check for unique path segment for path param name

docs/azure-ruleset.md, functions/readonly-in-response-schema.js, spectral.yaml, test/readonly-in-response-schema.test.js
This PR adds a rule to check for properties that are marked `readOnly: true` in schemas that are never used in a request body.
=> Add az-readonly-in-response-schema rule with test and docs

spectral.yaml
This PR is a minor fix to az-property-type that excludes properties that contain `allOf` to avoid a false positive when the `allOf` contains a $ref to a schema that has a defined type (a common situation).
=> Minor fix to az-property-type to avoid false positives

docs/azure-ruleset.md, spectral.yaml, test/lro-put-response-codes.test.js, test/lro-response-codes.test.js, test/lro-response-headers.test.js
This PR adds some rules to catch the most common and egregious issues with conformance to the updated Azure LRO guidelines.
- az-lro-get-not-allowed flags long-running gets
- az-lro-patch-not-allowed flags long-running patches
- az-lro-put-response-codes flags a put that returns 202
- az-lro-response-codes flags a long-running operation that also returns other 2XX responses
- az-lro-response-schema flags a 202 response without a schema
Docs updated and (some) tests added.
=> Update for new LRO guidelines

functions/security-requirements.js, test/security-requirements.test.js
Little fix to az-security-requirement to handle the case where an oauth2 scope is defined but the description is an empty string.
=> Fix az-security-requirement for scope with empty value

functions/readonly-in-response-schema.js, test/readonly-in-response-schema.test.js
This PR adds logic to search for polymorphic children of a request schema when constructing the full set of request schemas in the az-readonly-in-response-schema processing.
=> Check for polymorphic child schemas in search for request schemas

docs/azure-ruleset.md, spectral.yaml
This PR adds the az-request-body-type rule, which flags any request body whose top-level type is "array".
=> Add az-request-body-type rule

functions/patch-content-type.js
This PR makes a small change to the az-patch-content-type rule to also check for non-patch methods consuming JSON patch.
=> Update patch-content-type to check for JSON patch

spectral.yaml
This PR changes the az-schema-names-convention to allow "." characters as separators in schema names. TypeSpec qualifies schema names with the namespace and uses the "." separator, so this avoids flagging all these.
=> Relax schema name rule to allow optional . separator

spectral.yaml, test/request-body-optional.test.js
Minor update to the az-request-body-optional rule to avoid flagging a request body that explicitly specifies `required: false`.
=> Only flag optional request body if required is not specified

spectral.yaml, test/path-case-convention.test.js
This PR makes a minor fix to the az-path-case-convention rule to relax the pattern for the action part, after a ":", to not require kebab-case or any particular case convention.
=> Action in path does not need to be kebab-case

functions/pagination-response.js, test/pagination-response.test.js
This PR makes a little improvement to the az-pagination-response rule to check the `nextLink` property has `format: url`.
=> Check nextLink is format: url

docs/azure-ruleset.md, functions/schema-type-and-format.js, test/schema-type-and-format.test.js
This PR makes a small change to the az-schema-type-and-format rule to allow `format: uri` for string types. Autorest accepts `format: uri` as equivalent to `format: url`.
It's also worth noting that "uri" has been added to the [OpenAPI formats registry](https://spec.openapis.org/registry/format/).
Tests and documentation have been updated.
=> Allow format: uri for string types

functions/schema-type-and-format.js, test/schema-type-and-format.test.js
This PR is a little fix to the az-schema-type-and-format rule to recurse into array schema.
=> Recurse into arrays when checking schema type and format

functions/property-default-not-allowed.js, test/property-default-not-allowed.test.js
This PR fixes a bug in the propertyDefaultNotAllowed function that attempted to reference into `properties` without first ensuring it was defined. The fix is to use optional chaining.  I also added a test (as the first commit) to reproduce the problem.
=> Fix property default not allowed

functions/pagination-response.js, functions/param-names.js, functions/readonly-in-response-schema.js, spectral.yaml, test/pagination-response.test.js, test/readonly-in-response-schema.test.js
This PR contains a collection of little fixes I have been accumulating in my local repo:
- Allow `nextLink` format to be either `url` or `uri`
- Allow uppercase "ID" suffixes on header parameters e.g. Repeatability-Request-ID 
- Fix readonly-in-response function to properly handle operation with no parameters.
=> Collection of little fixes

functions/lro-response-schema.js, spectral.yaml, test/lro-response-schema.test.js
Update the az-lro-response-schema rule to check the properties of the response schema.
This was motivated by https://github.com/Azure/azure-rest-api-specs/pull/26634 which was missing the `error` property in its LRO response.
=> Add function to check properties of LRO response schema

docs/azure-ruleset.md, functions/put-request-and-response-body.js, spectral.yaml, test/put-request-and-response-body.test.js
This PR adds the az-put-request-and-response-body rule, which checks PUT operations to ensure that the schema for the request body matches the schema for the success (200 or 201) response body.
=> Add az-put-request-and-response-body rule with test and docs

functions/unused-definition.js, spectral.yaml, test/unused-definition.test.js
This PR adds the az-unused-definition rule as a replacement for oas2-unused-definition which gives many false positives on Azure API definitions, in particular for polymorphic schemas.
=> Replace oas2-unused-definition with az-unused-definition

spectral.yaml
This PR makes a small tweak to the az-patch-path rule so that the resulting `path` for a violation is the `patch` operation and not the whole pathItem.
=> Improve az-patch-patch rule

package-lock.json
This PR contains changes made by `npm audit fix`. Unfortunately `npm audit` still reports 2 high severity vulnerabilities, but offers no fix for them.
=> Fix some audit warnings

.github/workflows/node.js.yml
The GitHub action to run CI was configured to use old / deprecated versions of Node. This PR updates the action to use the currently supported versions of Node.
=> Update node versions in ci

.github/workflows/node.js.yml
CoPilot says I need this line to enable triggering the workflow with the gh CLI, which I need to do because the GitHub workflows pages is not showing me a "Re-run jobs" button (so frustrating).
=> Enable workflow dispatch

functions/param-names-unique.js, package-lock.json, package.json, test/datetime-naming-convention.test.js, test/header-disallowed.test.js, test/matchers.js, test/parameter-names-convention.test.js, test/parameter-names-unique.test.js, test/path-param-schema.test.js, test/schema-type-and-format.test.js
This is the same fix that was proposed by dependabot in #141 but I couldn't merge that one because of GitHub silliness.
Turns out that the new Spectral core changes the order of messages returned in some cases, so I had to update some tests to be resilient to that.
=> Update version of spectral core package
